server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5435/notification_db
clients.ticket-backend.url=http://localhost:8081
spring.kafka.bootstrap-servers=localhost:9092

logging.level.com.erdos.ticketapp=DEBUG
logging.level.org.apache.kafka.common.config.AbstractConfig=WARN
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,conditions,loggers,liquibase,mappings
